FROM cockroachdb/cockroach:latest as base
COPY src/schemas/replays.sql /docker-entrypoint-initdb.d/replays.sql
# CockroachDB listens on port 26257. Overwrite default EXPOSE that also exposes 8080
# EXPOSE 26257
CMD ["start-single-node", "--insecure"]